services:
  api:
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/app/app:ro

  bot:
    volumes:
      - ./app:/app/app:ro

  worker:
    volumes:
      - ./app:/app/app:ro
